language: java
services:
  - docker
sudo: false
jdk:
  - openjdk11
job:
  script:
    - mvn package -f test-data-provider-service/pom.xml
    - docker-compose build
    - sleep 5000
    - mvn test -f client/pom.xml

