language: java
services:
  - docker
sudo: false
jdk:
  - openjdk11
job:
  include:
    - stage: build application
      script: mvn package -f test-data-provider-service/pom.xml
    - stage: build docker
      script: docker-compose built

